name: SonarCloud Analysis

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # Run weekly on Mondays

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: SonarCloud Scan
        # Updated to use the recommended version
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-created by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Need to be added in GitHub secrets
        with:
          args: >
            -Dsonar.projectKey=example_cloudformation-poc
            -Dsonar.organization=jimmy622001
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.bat,**/*.sh
            -Dsonar.cfn.file.suffixes=.yaml,.yml,templates/**/*.yaml,templates/**/*.yml
            -Dsonar.cfn.nag.reportFiles=cfn-lint-results.sarif
            -Dsonar.branch.name=${{ github.ref_name }}